inc:
  # Blog Information
  title:        "MOL"
  subtitle:     "Designing for a Mobile World!"
  cover_image:  blog-cover.jpg
  logo:         logo.png
  
  # Company information
  company:      MOL
  url:          http://t32k.me/
  facebook:     t32k
  twitter:      t32k
  gplus:        '104886596569728254273'
  about_link:   http://t32k.me/
  
  # Product Information
  product_link: https://github.com/t32k/maple
  tagline:      "Realistic Sass-based CSS framework for mobile"
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false
  
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         false
    
  
 # Analytics     
  analytics:
    google: 
      # eg. 'UA-123-12'
      id:       'UA-2317436-26'
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://t32k.me/
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     /log/:title/
paginate_path: 'page:num'
paginate: 7

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator:

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /mol/
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /mol/assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false