DefaultContentLanguage = "ja"
baseurl = "https://t32k.me/mol/"
title = "MOL"
publishdir = "public"
MetaDataFormat = "yaml"
pygmentsCodeFences = true
[params]
  description = "Designing for User Interface"
  author = "Koji Ishimoto"
[markup.goldmark.renderer]
unsafe= true