baseurl = "http://t32k.me/mol/"
languageCode = "ja"
title = "MOL"
publishdir = "_public"

[indexes]
  category = "categories"

[params]
  description = "Designing for a Mobile World."
  author = "Koji Ishimoto"