version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - run:
          name: Update enviroment
          command: apk update && apk add git
      - run:
          name: System information
          command: echo "$(hugo version)"
      - checkout
      - run:
          name: Building blog pages
          command: |
            HUGO_ENV=production hugo -v
            cp public/index.xml public/feed.xml
      - add_ssh_keys:
          fingerprints:
            - "f8:a1:03:29:9f:5f:86:44:8e:10:17:5b:f9:20:37:1c"
      - deploy:
          name: Deploy to GitHub Pages
          command: ./.circleci/deploy.sh
